version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

configuration: Release

init:
- ps: >-
    $env:nuget_version = "$env:appveyor_build_version"

    if($env:appveyor_repo_tag -eq $true) {
      $env:nuget_version = "$env:appveyor_repo_tag_name"
    } else {
      $env:nuget_version = "$env:appveyor_build_version-dev"
    }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(nuget_version)
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(nuget_version)

nuget:
  project_feed: true

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  verbosity: minimal

test:
  assemblies:
    only:
    - '**\*.Tests.dll'

# before_package:
# - ps: dotnet pack $env:appveyor_build_folder/Bearded.UI/Bearded.UI.csproj --configuration Release /p:Version="$env:nuget_version"

artifacts:
- path: '**\*.nupkg'
  name: Nuget Packages

# deploy:
# - provider: NuGet
#   api_key:
#     secure: 80+P1cLUqTM+reRhqLzF2Lam3T807nNcrdPtYnBFG85FpgCQDUY5VQkYzRinctbj
#   on:
#     branch: /^master$/
